### ISSUE TITLE
схема в альтиуме

### ISSUE THREAD

**Issue by esaulenka** [ARNik/LIN_break#1]
Рома, добавь пожалуйста схему в pdf - для лентяев, которым лень ставить альтиум.

PS собирать эту штуку не буду - когда наконец припрёт аналогичная нужда, можно сделать на стмке и двух лин-драйверах. Можно даже сразу с передачей данных в sigrok (saleae мимо, т.к. у них протокол закрытый).

**Comment by ARNik** [comment]
Алексей, этот проект не завершен.
pdf добавил но на сколько это решение рабочее - не знаю.
Надо проверять.
